"""Data models for standalone invoice flow experimentation."""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from typing import Literal

from app.schemas import InvoiceItem

FlowMode = Literal["legacy", "shadow", "modular"]


@dataclass(frozen=True, slots=True)
class CatalogEntry:
    """Minimal catalog projection used by resolver experiments."""

    product_id: str
    name: str
    stock_unit: str | None = None
    category: str | None = None


@dataclass(frozen=True, slots=True)
class FlowSuggestion:
    """Suggestion generated by modular flow for a single row."""

    row_index: int
    source_unit: str | None
    target_unit: str | None
    source_quantity: Decimal | None
    target_quantity: Decimal | None
    factor: Decimal | None
    confidence: Literal["none", "low", "medium", "high"] = "none"
    reason: str = ""
    notes: tuple[str, ...] = ()


@dataclass(slots=True)
class FlowExecution:
    """Execution result for one mode."""

    mode: FlowMode
    output_items: list[InvoiceItem]
    legacy_items: list[InvoiceItem]
    modular_items: list[InvoiceItem]
    suggestions: list[FlowSuggestion] = field(default_factory=list)
    changed_rows: int = 0
    warnings: list[str] = field(default_factory=list)
